services:
  - type: web
    name: kokzhiek-editor-backend
    env: node
    plan: free
    rootDir: ./
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: kokzhiek-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: "Kokzhiek Editor"
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,http://localhost:5173,https://localhost:3000,https://localhost:5173,https://kokzhiek.icai.kz,https://kokzhiek-new.vercel.app"
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: SERVICE_VERSION
        value: 1.0.1

databases:
  - name: kokzhiek-db
    databaseName: kokzhiek
    user: kokzhiek_user
    plan: free