services:
  - type: web
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    env: node
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true